### ISSUE TITLE
This might make .WASM files smaller

### ISSUE THREAD

**Issue by daniellovera** [zhaohappy/cheap#1]
Hi. Cheap and libmedia are brilliant. I noticed lots of people unhappy about .WASM file size.

You can shrink them with Binyaren option --zero-filled-memory under wasm-opts

https://github.com/WebAssembly/binaryen/blob/main/src%2Ftools%2Foptimization-options.h#L302-L309

Hope that helps!

**Comment by zhaohappy** [comment]
It seems that the option --zero-filled-memory does not work for dynamically link mode. I got the warn ```warning: no passes specified, not doing any work``` and the file's size has not decreased.

But this gave me an inspiration, so I wrote a command tool to remove the zero data in the data segment, declared the actual size of the data segment in the custom segment , and used cheap to initialize the remaining memory to zero. Now these wasm files have become very small.

thanks.
